# Generated by Django 3.0.6 on 2020-05-24 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendances',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='classtypes',
            options={'ordering': ['class_type']},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['course_name']},
        ),
        migrations.RemoveField(
            model_name='users',
            name='teaching',
        ),
        migrations.AlterField(
            model_name='courses',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching', to=settings.AUTH_USER_MODEL),
        ),
    ]
