# Generated by Django 3.0.6 on 2020-05-24 18:51

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('attendance', '0002_auto_20200524_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
            ],
            options={
                'ordering': ['last_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
