# Generated by Django 3.0.6 on 2020-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200522_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='student_id',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
