# Generated by Django 3.0.6 on 2020-05-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200522_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='student_id',
        ),
    ]
