# Generated by Django 3.0.6 on 2020-05-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200523_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='date',
            field=models.DateTimeField(editable=False),
        ),
    ]
